name: modpoll-example-2

volumes:
  mosquitto-config-vol:
  mosquitto-data-vol:

services:
  modpoll:
    depends_on:
      - mosquitto
    image: topmaker/modpoll
    container_name: modpoll
    restart: unless-stopped
    volumes:
      - ./config/:/app/config/
    command: >
      modpoll -d --tcp 192.168.133.85
        --mqtt-host mosquitto
        --mqtt-publish-topic-pattern mytest/{{device_name}}/data
        --mqtt-qos 1
        --rate 30
        --timestamp
        --config config/my-device.csv

  mosquitto:
    image: topmaker/mosquitto:2.0.15
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - mosquitto-config-vol:/mosquitto/config
      - mosquitto-data-vol:/mosquitto/data
    ports:
      - 1883:1883
    environment:
      - MOSQUITTO_USERNAME=${MQTT_USERNAME}
      - MOSQUITTO_PASSWORD=${MQTT_PASSWORD}
